version: "3.7"
services:
  template-service:
    image:
    container_name: template-service
    hostname: template-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500

